core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inua.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inua/urls.py
from django.urls import path
from .views import HomePageView,AboutUsView,ActivityPageView

app_name = 'inua'

urlpatterns = [
    path('',HomePageView.as_view(),name='homepage'),
    path('activity/',ActivityPageView.as_view(),name='activity'),
    path('aboutus/',AboutUsView.as_view(),name='aboutus'),
]

inua/models.py
from django.db import models
class Program(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300,unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='uploads/programs-pics/')

    def __str__(self) -> str:
        return self.title

class Activity(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=300,unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='uploads/activity-pics/')
    program = models.ForeignKey(Program, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title


class AboutUs(models.Model):
    description = models.TextField()
    vision = models.CharField(max_length=255)
    mission = models.CharField(max_length=400)

inua/views.py
from django.shortcuts import render,get_object_or_404

# Create your views here.
from django.views.generic import TemplateView,ListView
from .models import Program,AboutUs,Activity


class HomePageView(ListView):
    template_name = 'homepage.html'
    model = Program
    context_object_name = 'programs'


class ActivityPageView(ListView):
    model = Activity
    template_name = 'activity.html'
    context_object_name =  'activitys'

    def get_queryset(self):
        program_slug = self.kwargs.get('program_slug')
       
        program = get_object_or_404(Program, slug=program_slug)
        queryset = super().get_queryset().filter(program = program)
        return queryset
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['program'] = self.program
        context['programs'] = Program.objects.all()
        return context



class AboutUsView(ListView):
    template_name = 'about.html'
    model = AboutUs
    context_object_name = 'aboutus'

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section>
    {% for about in aboutus %}
    <div class="about-us-heading">
        <h1>About Us</h1>
        <p>INUA COLLECTIVE  SOCIETY</p>
    </div>  
     
    <div class="about-us-main-body">
        <img src="{% static 'images/about_us.jpg' %}">
       
        <div class="about-us-main-content">
            <h2>INUA COLLECTIVE SOCIETY</h2>
            <p>{{ about.description }}</p>
        </div>   
    </div>
    <div class="container">
        <div class="mission">
            <img src="{% static 'images/icons8-goal-50.png' %}">
            <div class="mission-name">
                <h2>MISSION</h2>
            </div>
            <div class="about-mission">
                <p>{{ about.mission}}</p>
            </div>
        </div>
        <div class="vision">
            <img src="{% static 'images/icons8-vision-64.png' %}">
            <div class="vision-name">
                <h2>VISION</h2>
            </div>
            <div class="about-vision">
                <p>{{ about.vision}}</p>
            </div>
        </div>
        <div class="core-values">
         
            <img src="{% static 'images/icons8-diamonds-64 (1).png' %}">
            <div class="core-values-name" >
                <h2>CORE VALUES</h2>
            </div>
            <div class="about-corevalues">
                <ul>
                    <li>Innovation</li>
                    <li>Integrity</li>
                    <li>Dignity</li>
                    <li>Partnership & Collaborations</li>
                    <li>Inclusic</li>
                    
                </ul>
            </div>
        </div>
    </div>   
    {% endfor %}
</section> 

{% endblock %}

templates/aboutus.html
{% load static %}
<section>
    <div class="about-us-body">
        <img src="{% static 'images/about_us.jpg'%}">
        <div class="about-content">
            <h2>INUA COLLECTIVE SOCIETY</h2>
            <p>is a non-profit organization with
            operations in the BC Lower mainland. INUA is a Swahili word which
            translates to elevate or uplift. INUA Collective society strives to
            elevate and up-skill the welfare of BIPOC and other racialized
            communities in BC lower mainland. INUA Collective Society hopes
            to achieve its goal through supporting, showcasing, and
            empowering the communities they work with through Arts, Sports,
            capacity building and entrepreneurship.</p>
            <div  class="aboutus-more-btn"><a href="{% url 'inua:aboutus' %}">Learn More</a></div>
        </div>
</section>

templates/activity.html
{% extends 'base.html' %}
{% block content %}
<div>
   {% for p in programs %}
   <h1>{{ p.title }}</h1>
   {% endfor %}
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inua collective society</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">   
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    

</head>
<body>
    <header>
        <img class="logo" src="{% static 'images/inua_logo.png' %}">
        <h2 class="logo-head">
            INUA 
        </br>
            COLLECTIVE 
        </br>
            SOCIETY
        </h2>
        <div class=" bx bx-menu" id="menu-icon"></div>
        <ul class="navbar">
            <li><a href="{% url 'inua:homepage' %}">Home</a></li>
            <li><a href="#">Programs</a>
                <div class="sub-menu-1">
                    <ul>
                        <li><a href="#">Youth Empowerment, Mentorship and Welness</a></li>
                        <li><a href="#">Community Advocacy, Empowerment and Development</a></li>
                        <li><a href="#">Arts, Sports and Culture Development</a></li>
                    </ul>   
                </div>
            </li>
            <li><a href="#">Events</a></li>
            <li><a href="#">Board Members</a></li>
            <li><a href="#">Gallery</a>
                <div class="sub-menu-1">
                    <ul>
                        <li><a href="#">Youth Empowerment, Mentorship and Welnes Gallery</a></li>
                        <li><a href="#">Community Advocacy, Empowerment and Development Gallery</a></li>
                        <li><a href="#">Arts, Sports and Culture Development Gallery</a></li>
                    </ul>      
                </div>
            </li>
            <li><a href="{% url 'inua:aboutus' %}">About Us</a></li>
        </ul>
    </header>
    {% block content %}
    {% endblock %}      
    <footer>
        <div class="footer-container">
            <div class="left-footer">
                <div>
                    <i class="fa fa-map-marker"></i>
                    <p><span>9343-149 st</span>
                    Surrey BC</p>
                </div>
                <div>
                    <i class="fa fa-phone"></i>
                    <p><span>+604 616 5717</span>236-558-8300</p>
                </div>
                <div>
                    <i class="fa fa-envelope"></i>
                    <p><a href="inuacollective@gmail.com"></a>inuacollective@gmail.com</p>
                </div>
                <div>
                    <i class="fa fa-cell"></i>
                </div>
            </div>
            <div class="right-footer">
                <div class="follow-us">
                    <h3 >
                        Connect with Us
                    </h3>
                </div>
                
                <div class="socials-icons">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                    <a href="#"><i class="fa fa-tiktok"></i></a>
                    <a href="#"><i class="fa fa-linkedin-in"></i></a>
                </div>
            </div>
        </div> 
        <div class="footer-bottom">
            <p>Copyright &copy;2023; <span class="designer">INUA COLLECTIVE SOCIETY</span></p>
        </div>    
        <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% block content %}
{% include 'aboutus.html' %}
<h2 class="program-c">Programs</h2>
<div class="programs-dv">
    
    {% for program in programs %}
   
    <div class="program">
        <h4>{{ program.title }}</h4>

            <img class="program-img" src="{% if program.image %}{{ program.image.url }}{% endif %}">
        <p>{{ program.description|linebreaks }}</p>

    </div>
    {% endfor %}
</div>
{% endblock %}